name: Bug à corriger
description: Signalez un bug à corriger
title: "[Bug]: [Description du bug]"
labels: ["bug", "help wanted"]

body:
  - type: markdown
    attributes:
      value: |
        # Description du bug
  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: En quoi consiste ce bug ?
      placeholder: ex. "Le pipe ne fonctionne pas lors de l'execution d'une commande."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Quel comportement attendez-vous ?
      placeholder: ex. "Le pipe doit passer le résultat de la commande précédente lors de l'execution d'une commande."
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Comportement actuel
      description: Quel comportement obtenez-vous ?
      placeholder: ex. "Le pipe ne passe pas le résultat de la commande précédente lors de l'execution d'une commande."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Etapes pour reproduire le bug
      description: Comment reproduire le bug ?
      placeholder: ex. "1. Lancer la commande `echo 'Hello World' | cat`"
    validations:
      required: true
